# Generated by Django 2.1.2 on 2018-10-31 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foo',
            options={'managed': False},
        ),
    ]
